### ISSUE TITLE
教程地址失效

### ISSUE THREAD

**Issue by Sciroccogti** [xmy0916/racecar#1]
https://github.com/xmy0916/racecar/blob/f49f076ed63b6b308652e989bd9f92477e3a2b8c/README.md#L2

此处地址已失效！

**Comment by xmy0916** [comment]
@Sciroccogti https://www.guyuehome.com/6463新地址，有空我修改下，谢谢了

**Comment by sugar-Steamedfish** [comment]
> [https://www.guyuehome.com/6463 新地址，有空我修改下，谢谢了](https://www.guyuehome.com/6463%E6%96%B0%E5%9C%B0%E5%9D%80%EF%BC%8C%E6%9C%89%E7%A9%BA%E6%88%91%E4%BF%AE%E6%94%B9%E4%B8%8B%EF%BC%8C%E8%B0%A2%E8%B0%A2%E4%BA%86)

您好，又失效了
